POST http://localhost:5000/sign-in
content-type: application/json

{
    "login": "Admin",
    "password": "0987654321"
}

###

GET http://localhost:5000/api/pumping-stations/list-by-account-id/bdc0d605-e7b9-4798-9167-65556ca069fb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc0MDExNzF9.gtAq0WtKSWa3Nkka9lqHPTffBuqZwsohO6iu-sCRkYg
X-Requested-User: Admin

###

GET http://localhost:5000/api/pumping-stations/state/1b2210ac-ab3a-466b-a065-1dc2a7abeac3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc0MDExNzF9.gtAq0WtKSWa3Nkka9lqHPTffBuqZwsohO6iu-sCRkYg
X-Requested-User: Admin

###

GET http://localhost:5000/api/pumping-stations/1b2210ac-ab3a-466b-a065-1dc2a7abeac3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc0MDExNzF9.gtAq0WtKSWa3Nkka9lqHPTffBuqZwsohO6iu-sCRkYg
X-Requested-User: Admin

###

POST http://localhost:5000/api/pumping-stations/state/1b2210ac-ab3a-466b-a065-1dc2a7abeac3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc0ODUwOTB9.xF7LNeUeCgT5s_AYf2rhkHhpjmOjFHm9T1moE5bh5ho
X-Requested-User: Admin
content-type: application/json

{
    "propName": "reset_operating_time_pump_2",
    "value": false
}