FROM node:bullseye AS build

WORKDIR /app
COPY . /app/

RUN npm install --legacy-peer-deps
RUN npm run build


FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]