FROM node AS build

WORKDIR /app
COPY . /app/

ARG REACT_APP_WEB_API_PORT=5001
ENV REACT_APP_WEB_API_PORT=$REACT_APP_WEB_API_PORT

RUN npm install --legacy-peer-deps
RUN npm run build

FROM nginx:alpine AS main

RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]